// <auto-generated />
using System;
using AspNetCoreZhao.WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspNetCoreZhao.WebApi.Migrations
{
    [DbContext(typeof(RoutineDataContext))]
    [Migration("20200322103103_emlpoyeeDto")]
    partial class emlpoyeeDto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("AspNetCoreZhao.WebApi.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Introduction")
                        .HasColumnType("TEXT")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f47e01a-c072-427d-a5a6-27a8ae96380e"),
                            Introduction = "Great Company",
                            Name = "Microsoft"
                        },
                        new
                        {
                            Id = new Guid("35ca78f2-d595-4890-93c4-db6d5d258f5c"),
                            Introduction = "No Company",
                            Name = "Google"
                        },
                        new
                        {
                            Id = new Guid("6f6cbfb0-11c2-45c8-ab77-49b04070a919"),
                            Introduction = "TuBaolan Company",
                            Name = "Alibaba"
                        });
                });

            modelBuilder.Entity("AspNetCoreZhao.WebApi.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<int>("gender")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e3d1f618-1599-4b13-b25b-793a4aa8b54a"),
                            CompanyId = new Guid("0f47e01a-c072-427d-a5a6-27a8ae96380e"),
                            DateOfBirth = new DateTime(1976, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "0321",
                            FirstName = "123",
                            LastName = "456",
                            gender = 1
                        },
                        new
                        {
                            Id = new Guid("a1bb1375-b7de-4a5f-8954-71a61595b9fd"),
                            CompanyId = new Guid("35ca78f2-d595-4890-93c4-db6d5d258f5c"),
                            DateOfBirth = new DateTime(1976, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "0321",
                            FirstName = "098",
                            LastName = "124",
                            gender = 1
                        });
                });

            modelBuilder.Entity("AspNetCoreZhao.WebApi.Entities.Employee", b =>
                {
                    b.HasOne("AspNetCoreZhao.WebApi.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
